name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar Cypress
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          build: npm run build
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60

      - name: Upload de artefatos (Cypress)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Cypress Results
          path: |
            cypress/screenshots
            cypress/videos
            cypress/results
          if-no-files-found: ignore
